### ISSUE TITLE
ダンジョンモデル作成

### ISSUE THREAD

**Issue by riwn** [riwn/shiren2-bot#13]
推測だが、ダンジョンごとにモンスターの出方とかアイテムの出方とか変わるので必要になると思われる。
シュテン山(初級・中級・上級)
鬼ヶ島
中腹の井戸
神社の隠し穴
開かずの間
最果てへの道

**Comment by fokkuma** [comment]
ER図って簡単なものでもありますか？ソースから読み取る感じ？
優先度にもよりますがやりたいです。

**Comment by riwn** [comment]
@fokkuma 今のところアイテムしかモデルないんでER図ないっす！
それを軸にER図作らないとダメっすねー

まあでも、ダンジョンとアイテムの間、ダンジョンとモンスターの間に中間テーブルが入るイメージをしてるので、ダンジョンモデル自体はアイテムモデルを参考に作ってもらえればって感じですかね

必要な情報は一旦モックできた後でみんなでレビューしましょうか

**Comment by fokkuma** [comment]
@riwn それは失礼しました…。

じゃあ、モック作成してみます！できれば今週中にやりますー

**Comment by fokkuma** [comment]
@riwn こんな感じで大丈夫ですか？方向性間違ってないか確認です。
![image](https://user-images.githubusercontent.com/49399218/112160771-d8951d00-8c2d-11eb-9511-db6909b34d75.png)

**Comment by riwn** [comment]
アイテムはそれで大丈夫。
中間モデルは後で考えるとして、次はダンジョンに必要な要素かな

**Comment by yushiray** [comment]
懐かしい図だw

ダンジョンはぱっときれいな形が思い浮かばない
- id
- name
- floor
まではたぶんあって
モンスターテーブルの参照が難しい。
後はアイテムが店床変化とかですかね。

**Comment by fokkuma** [comment]
ありがとうございます。Wikiも見たりして考えてみましたけど、用途とか拡張性？とか気にすると不足しているかなと思いつつ…
申し訳程度にモンスターテーブルとキャラクターテーブル（シレン＋味方）も考えてみました。drawioのファイル添付できなかったので画像ですがm(__)m
![ER図_たたき台](https://user-images.githubusercontent.com/49399218/112323244-f24d6780-8cf4-11eb-824a-e592f8341b1b.PNG)

**Comment by riwn** [comment]
キャラクターはレベルでモデル分けましょ
1～100までのステータス全然違うんよね

**Comment by riwn** [comment]
ダンジョンもフロアでモデル分けた方がいいんかなー

でも、これRDSの考え方してそう。。

**Comment by fokkuma** [comment]
すみません、#14を対応して一息ついちゃいました。Gitに上げたので目を通してもらえればと思います。

**Comment by yushiray** [comment]
PCがぶっ壊れていて全然見れてませんでした。
ありがとうございます。
