### ISSUE TITLE
TypeScriptに置き換え

### ISSUE THREAD

**Issue by riwn** [riwn/shiren2-bot#2]
時代はtsっしょ
https://qiita.com/notakaos/items/3bbd2293e2ff286d9f49

**Comment by yushiray** [comment]
一気に置き換えるのは難しいので
ディレクトリ構成を変えてsrcに今のコードを持ってきて
distに出力するようにするのが収まりがいいですかね

**Comment by riwn** [comment]
参考にしてみます！
TypeScript触ったことないんでとりあえず今週末にでもちょっと構成考えて環境作ってみますね

**Comment by riwn** [comment]
別のリポジトリ触ってたら土日消え去ったので平日の仕事終わりにやりますw

**Comment by riwn** [comment]
やっと手つけれました。
一旦typescript導入してsrcに全部ソース移したのをコミットしてます。
ちょっとずついじって行こうかと

**Comment by yushiray** [comment]
最近Rust言語100本ノックに浮気してましたｗ
見ます
