### ISSUE TITLE
値段検索機能の追加

### ISSUE THREAD

**Issue by riwn** [riwn/shiren2-bot#3]
値段を入力したら検索できる機能を追加

**Comment by yushiray** [comment]
買値検索コマンド
売値検索コマンド
を作って各アイテムのクラスに検索用の関数を実装するのがよさげ？
ちょっと武器盾が合わないので微妙

**Comment by riwn** [comment]
引数は種類(草とか杖とか)と値段のふたつで良いと思います。
武器盾の検索少し難しそうですが基本-1～+3
までで出るのでその間を検索してあげるのが良いかと。

**Comment by yushiray** [comment]
案1
今の各アイテムのClass名にsが接頭辞についてますが扱っているのは単体なので
例えば
scrollsクラスとscrollクラスに分けて関数の実装を分ける（itemsクラスをどうするかといのはありますが）

案2
今の実装で例えばscrollsクラスにthis.scrollsをインスタンス化する時にundefinedで初期化しておき
値段を渡したときに該当するscrollのitemlistをsetする関数を書く
さらにそのlistを整形して出力する関数を実装。
commandの中では引数でswitchなりで分岐させて
各種アイテムのクラスをインスタンス化して値段検索を行う

ですかね

**Comment by riwn** [comment]
案2はかなりスッキリしそうですね
リファクタリングも含めてやるのが良さそうですね
ちょっとアイテムモデルは安易に作っちゃった感はありますね

**Comment by yushiray** [comment]
ちょっとサンプルを明日あたりでも作ってみますね

**Comment by riwn** [comment]
巻物サンプル追加済
#12
